export enum EInputType {
    Text = "text",
    Password = "password",
    Email = "email",
    Number = "number",
    Tel = "tel",
    Url = "url",
    Date = "date",
    Time = "time",
    DatetimeLocal = "datetime-local",
    Month = "month",
    Week = "week",
    Search = "search",
    Color = "color",
    File = "file",
    Checkbox = "checkbox",
    Radio = "radio",
    Range = "range",
    Hidden = "hidden",
    Submit = "submit",
    Reset = "reset",
    Button = "button",
    Image = "image",
  }